// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvM6TxxqJy6vObCF2Qf9pBWFiVRJx4QT8',
    appId: '1:62990481402:web:67ecb3a5556a31e16e1643',
    messagingSenderId: '62990481402',
    projectId: 'poemer-f4001',
    authDomain: 'poemer-f4001.firebaseapp.com',
    storageBucket: 'poemer-f4001.appspot.com',
    measurementId: 'G-VVMKMVVKC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD33C52SadmRrN2WKY6PPTtZgmcV2VfnC0',
    appId: '1:62990481402:android:8ca153c65f1fc0346e1643',
    messagingSenderId: '62990481402',
    projectId: 'poemer-f4001',
    storageBucket: 'poemer-f4001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjIHdMOe_d-xlvnBaGDP3uxUjZXTmRfkY',
    appId: '1:62990481402:ios:3b3b6209187804506e1643',
    messagingSenderId: '62990481402',
    projectId: 'poemer-f4001',
    storageBucket: 'poemer-f4001.appspot.com',
    iosClientId: '62990481402-jeu0usna1917pj7o6g79116g0hi3vkmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.poemer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjIHdMOe_d-xlvnBaGDP3uxUjZXTmRfkY',
    appId: '1:62990481402:ios:3b3b6209187804506e1643',
    messagingSenderId: '62990481402',
    projectId: 'poemer-f4001',
    storageBucket: 'poemer-f4001.appspot.com',
    iosClientId: '62990481402-jeu0usna1917pj7o6g79116g0hi3vkmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.poemer',
  );
}
